Set selected volume to last logged volume
niklashedstrom/norrlandsordern pull request #27
Opened 2021-12-03 19:23 UTC by simonhyttfors

Placerar helt enkelt `selected`-attributet i `select`-listan på den senast loggade volymen

2021-12-03 20:35 UTC, emilwihlander requested changes
Tre saker:

Det gamla är en klass och det nya är ett attribut, vet inte om det har några implikationer 

Ser hellre att man skickar in en variabel som heter typ "lastUsedVolume" som används för att det ska vara enklare att läsa

Borde inte "norrlands[0].volume == '33' ? true : false" vara samma som "norrlands[0].volume == '33'"?

2021-12-04 08:36 UTC, simonhyttfors commented
> Borde inte "norrlands[0].volume == '33' ? true : false" vara samma som "norrlands[0].volume == '33'"?

Det här är legit något av det pinsammaste jag någonsin har gjort

2021-12-04 08:41 UTC, emilwihlander commented
Hahaha, valde att skriva det som en fråga för att inte trycka på det allt för mycket

2021-12-04 13:00 UTC, emilwihlander approved these changes
LGTM 🎉

2021-12-04 14:04 UTC, merged